#!/usr/bin/env node
/* _dt_build.cjs — generate the "downtown-showdown" TANK BATTLE arena and patch it into
   assets/farmkart-track.js between the DOWNTOWN SHOWDOWN START/END markers.

   The SAME building footprint list emits BOTH the visual (the game derives lit-window boxes
   from each ghostWall rectangle) AND the collision (the ghostWall itself), so they can never
   drift apart. Re-run after editing the params below:  node tools/_dt_build.cjs
*/
const fs = require('fs');
const path = require('path');

const TRACK_JS = path.join(__dirname, '..', 'assets', 'farmkart-track.js');

// ---- arena params -------------------------------------------------------------------------
const HALF = 60;              // arena half-extent (world units)
const PERIM = 58;             // perimeter wall inset (karts stop just inside the visual edge)

// A broken city-block grid. Block-center coords along each axis + the block half-size there.
// Streets are the 16u gaps BETWEEN blocks (x/z = -30, 0, +30 run clear). The central crossroads
// (around the origin) is the plaza.
const AXIS = [
  { c: -48, h: 10 },   // outer block (touches the perimeter corner)
  { c: -15, h: 7  },   // inner block (frames the central plaza)
  { c:  15, h: 7  },
  { c:  48, h: 10 },
];

// deterministic per-building height (a varied skyline). indexed by (ix*4+iz).
const HEIGHTS = [26,18,20,30, 16,12,14,22, 22,14,12,18, 28,20,18,24];

// item boxes at the street intersections (all clear) incl. the central plaza.
const BOX_COORDS = [-30, 0, 30];

// centerline loop: a rounded rectangle threading the ring streets (|x|,|z| ~ 30). OFF-ROAD, so
// this is only the minimap route + progress + the spawn line — karts drive the whole ground.
const LOOP = [
  [0,30],[20,30],[30,20],[30,0],[30,-20],[20,-30],
  [0,-30],[-20,-30],[-30,-20],[-30,0],[-30,20],[-20,30]
];

// ---- build the data -----------------------------------------------------------------------
function rect(cx, cz, hx, hz){
  return [
    {x:+(cx-hx).toFixed(1), z:+(cz-hz).toFixed(1)},
    {x:+(cx+hx).toFixed(1), z:+(cz-hz).toFixed(1)},
    {x:+(cx+hx).toFixed(1), z:+(cz+hz).toFixed(1)},
    {x:+(cx-hx).toFixed(1), z:+(cz+hz).toFixed(1)},
    {x:+(cx-hx).toFixed(1), z:+(cz-hz).toFixed(1)},   // closed
  ];
}

const ghostWalls = [];
// perimeter (arena boundary)
ghostWalls.push({ id:'perim', points: rect(0, 0, PERIM, PERIM) });
// buildings
let bi = 0;
for (let ix=0; ix<AXIS.length; ix++){
  for (let iz=0; iz<AXIS.length; iz++){
    const bx = AXIS[ix], bz = AXIS[iz];
    const h = HEIGHTS[ix*4+iz] || 18;
    ghostWalls.push({ id:'bld_'+h, points: rect(bx.c, bz.c, bx.h, bz.h) });
    bi++;
  }
}

const battleBoxes = [];
for (const x of BOX_COORDS) for (const z of BOX_COORDS) battleBoxes.push({ x, z });

const points = LOOP.map(([x,z]) => ({ x, z, y: 0 }));

const track = {
  v: 1, name: 'Downtown Showdown', width: 20, laps: 1, gridSide: 'left',
  offroad: true, battle: true, tankBattle: true, sky: 'night', theme: 'city',
  points, battleBoxes, ghostWalls,
};

// ---- serialize compactly (points/battleBoxes one line each; ghostWalls one per line) ------
function j(o){ return JSON.stringify(o); }
const lines = [];
lines.push('    "downtown-showdown": {');
lines.push('      v:1, name:"Downtown Showdown", width:20, laps:1, gridSide:"left",');
lines.push('      offroad:true, battle:true, tankBattle:true, sky:"night", theme:"city",');
lines.push('      points:' + j(points) + ',');
lines.push('      battleBoxes:' + j(battleBoxes) + ',');
lines.push('      ghostWalls:[');
ghostWalls.forEach((g,i) => {
  lines.push('        ' + j(g) + (i<ghostWalls.length-1 ? ',' : ''));
});
lines.push('      ]');
lines.push('    },');
const block = lines.join('\n');

// ---- patch into track.js ------------------------------------------------------------------
const START = '// === DOWNTOWN SHOWDOWN START (generated by tools/_dt_build.cjs) ===';
const END = '// === DOWNTOWN SHOWDOWN END ===';
let src = fs.readFileSync(TRACK_JS, 'utf8');
const si = src.indexOf(START), ei = src.indexOf(END);
if (si < 0 || ei < 0){ console.error('markers not found in track.js'); process.exit(1); }
const head = src.slice(0, si + START.length);
const tail = src.slice(ei);
src = head + '\n' + block + '\n    ' + tail;
fs.writeFileSync(TRACK_JS, src);
console.log('patched downtown-showdown:', ghostWalls.length + ' ghostWalls ('+bi+' buildings + perimeter), '+battleBoxes.length+' item boxes, '+points.length+' loop points');
